language: go
go:
  - 1.7
  - 1.7.1
  - 1.7.3
  - 1.7.4
  - 1.8
  - 1.9

script:
  - go test -coverprofile=html_coverage.txt -covermode=atomic ./html
  - go test -coverprofile=xml_coverage.txt -covermode=atomic ./xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  apt:
    packages:
    - libxml2-dev
    - libonig-dev
